# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_user_window(object):
    def setupUi(self, New_user_window):
        New_user_window.setObjectName("New_user_window")
        New_user_window.resize(274, 173)
        self.centralwidget = QtWidgets.QWidget(New_user_window)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.Name_label = QtWidgets.QLabel(self.centralwidget)
        self.Name_label.setObjectName("Name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Name_label)
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setObjectName("name_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line)
        self.User_label = QtWidgets.QLabel(self.centralwidget)
        self.User_label.setObjectName("User_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.User_label)
        self.user_line = QtWidgets.QLineEdit(self.centralwidget)
        self.user_line.setObjectName("user_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.user_line)
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setObjectName("create_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.create_button)
        self.Password_label = QtWidgets.QLabel(self.centralwidget)
        self.Password_label.setObjectName("Password_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Password_label)
        self.password_line = QtWidgets.QLineEdit(self.centralwidget)
        self.password_line.setObjectName("password_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password_line)
        New_user_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(New_user_window)
        QtCore.QMetaObject.connectSlotsByName(New_user_window)

    def retranslateUi(self, New_user_window):
        _translate = QtCore.QCoreApplication.translate
        New_user_window.setWindowTitle(_translate("New_user_window", "MainWindow"))
        self.Name_label.setText(_translate("New_user_window", "Name :"))
        self.User_label.setText(_translate("New_user_window", "User :"))
        self.create_button.setText(_translate("New_user_window", "Create"))
        self.Password_label.setText(_translate("New_user_window", "Password :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    New_user_window = QtWidgets.QMainWindow()
    ui = Ui_New_user_window()
    ui.setupUi(New_user_window)
    New_user_window.show()
    sys.exit(app.exec_())
